### Create User
POST http://localhost:3000/api/v1/auth/register
Content-Type: application/json

{
    "name": "ykohl",
    "email": "keviny@gmail.com",
    "password": "123"
}

### Login User
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
    "email": "ykohleducation@gmail.com",
    "password": "0da35eb3332d3ede"
}

### login token
GET http://localhost:3000/api/v1/auth/authenticate
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6Inlrb2hsIiwiZW1haWwiOiJrZXZpbnlAZ21haWwuY29tIiwiYmlvIjpudWxsLCJpYXQiOjE3NDI1NzE5MDd9.PiVts0LDkGHudyJj08hY0Cj6MTnrsITHEsvdqeNM4J0

### Get all user
GET http://localhost:3000/api/v1/users

### Get all user by search
GET http://localhost:3000/api/v1/users?search=kevin

### profile
GET http://localhost:3000/api/v1/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6Inlrb2hsIiwiZW1haWwiOiJrZXZpbnlAZ21haWwuY29tIiwiYmlvIjpudWxsLCJpYXQiOjE3NDI1NzE5MDd9.PiVts0LDkGHudyJj08hY0Cj6MTnrsITHEsvdqeNM4J0

### profile
PUT http://localhost:3000/api/v1/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwibmFtZSI6Inlrb2hsIiwiZW1haWwiOiJrZXZpbnlAZ21haWwuY29tIiwiYmlvIjpudWxsLCJpYXQiOjE3NDExOTE2NzJ9.gNQWhHXumijQ0uSNVGQQCE2opD_OSHy-83KPJ4MIy0Y

{
    "name": "Kevin Y",
    "email": "keviny@gmail.com",
    "bio": "I am a software engineer"
}
