### Create User
POST http://localhost:3000/api/v1/auth/register
Content-Type: application/json

{
    "name": "noi",
    "email": "noi@gmail.com",
    "password": "123"
}

### Create User
POST https://tmdb-list-movie-with-apis-backend.vercel.app
/api/v1/auth/register
Content-Type: application/json

{
    "name": "noi",
    "email": "noi@gmail.com",
    "password": "123"
}

### Login User
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
    "email": "keviny@gmail.com",
    "password": "123"
}

### login token
GET http://localhost:3000/api/v1/auth/authenticate
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJrZXZpbnlvaGFuZXN0ZWVuQGdtYWlsLmNvbSIsIm5hbWUiOiJLZXZpbiBZb2hhbmVzIiwiaWF0IjoxNzQyNzQ4MTU5LCJleHAiOjE3NDMzNTI5NTl9.X5q4-DNUgmGUBm7hBnSSSrFZ-rmvRlaKPaKCW8Ha5Ps

### Get all user
GET https://tmdb-list-movie-with-apis-backend.vercel.app/api/v1/users

### Get all user by search
GET http://localhost:3000/api/v1/users?search=kevin

### profile
GET http://localhost:3000/api/v1/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6IktldmluIFkiLCJlbWFpbCI6ImtldmlueUBnbWFpbC5jb20iLCJiaW8iOiJJIGFtIGEgc29mdHdhcmUgZW5naW5lZXIiLCJhZGRyZXNzIjoiamwuIGphbGFuIiwib2NjdXBhdGlvbiI6InBvbGljaSIsImF2YXRhcl91cmwiOm51bGwsImdvb2dsZWlkIjoiMTE3ODE2MTM4NjEzNDMzMjAwODIzIiwiY3JlYXRlZEF0IjoiMjAyNS0wMy0yM1QxNTo1NTo0MC4wODhaIiwidXBkYXRlZEF0IjoiMjAyNS0wMy0yNlQxNjo1ODoxOS4zMzBaIiwiaWF0IjoxNzQzMDA4MzU2fQ.1RVpH4OW96hdNHUo2-3F2AmhK_JFlIJSEFIWUoStc0A

### profile
PUT http://localhost:3000/api/v1/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6IktldmluIFlvaGFuZXMiLCJlbWFpbCI6ImtldmlueW9oYW5lc3RlZW5AZ21haWwuY29tIiwiYmlvIjoiaGFpIGhhaSIsImFkZHJlc3MiOm51bGwsIm9jY3VwYXRpb24iOm51bGwsImF2YXRhcl91cmwiOm51bGwsImdvb2dsZWlkIjoiMTE3ODE2MTM4NjEzNDMzMjAwODIzIiwiY3JlYXRlZEF0IjoiMjAyNS0wMy0yM1QxNTo1NTo0MC4wODhaIiwidXBkYXRlZEF0IjoiMjAyNS0wMy0yNlQxNjo0MjowMC4yMTZaIiwiaWF0IjoxNzQzMDA3MzYzfQ.eEIwP3WKz2HTLxQHO78jvDmYKsahizWV7Jg1mX1rMwU

{
    "name": "Kevin Y",
    "email": "keviny@gmail.com",
    "bio": "I am a software engineer",
    "address": "Jakartaa",
    "occupation": "Software Engineer"
}

### oauth
GET http://localhost:3000/api/v1/auth/google/callback

### Set password
POST http://localhost:3000/api/v1/set-password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJrZXZpbnlvaGFuZXN0ZWVuQGdtYWlsLmNvbSIsIm5hbWUiOiJLZXZpbiBZb2hhbmVzIiwiaWF0IjoxNzQyNzQ4MTU5LCJleHAiOjE3NDMzNTI5NTl9.X5q4-DNUgmGUBm7hBnSSSrFZ-rmvRlaKPaKCW8Ha5Ps

{
    "password": "123"
}